### Data Cleaning Questions

- How do we consolidate `Week` and `Location` data from the 2016 filenames to the final 2016 DataFrame?

## Steps for Cleaning All Data:
---
- Step 1: Clean the 2016 Data (Weeks 1-7) into One DataFrame.
- Step 2: Clean the 2016 Data (Weeks 8) into One DataFrame.
- Step 2.5: Aggregate both 2016 Datasets (Weeks 1-7 and Week 8) into One Bigger DF (Weeks 1-8).
- Step 3: Clean the 2017 Data into One DataFrame.
- Step 3.5: Aggregate the 2016 DataFrame (Weeks 1-8) and the 2017 DF into One Biggest DF (2016-17). 


### Observation that 4/5 may not be exactly equivalent to 8/10 as it is to 9/10...

- [`STRETCH`] Try both scenarios on any related questions!

## What is Cleaning?

- Some data might be irrelevant, redundant, null, nonsensical
- Cleaning involves the steps to reduce the noise in a dataset
- CLEANING: Converting a ton of noise, extracting _signal_, and ending up with a **single source of truth**
- Signal is data that is valuable towards answering a question; extracting signal is our end goal in all types of data science


# Kash Cleaning Tips


### Understand what a column (feature) is truly communicating 
- Examples: [1-5] scale vs. [1-10] vs. "A little too slow" text scale, 

### NULL Values (NaNs)
- 

In [2]:
import glob
import pandas as pd 
import numpy as np
import os

In [4]:
# df16 = [pd.read_csv(f) for f in glob.glob('./SA Feedback Surveys_FINAL/2016/*.csv')]

all_csvs = glob.glob(os.path.join('./SA Feedback Surveys_FINAL/2016/', "*.csv"))
read_all_csvs = (pd.read_csv(f) for f in all_csvs)
df = pd.concat(read_all_csvs, ignore_index = True, sort = True)
df.head()

the_bad_thing = np.nan
type(the_bad_thing)

float

# To-Do List
- [ ] Check all columns to see if they have valid responses
- [ ] #REF! rows invalid
- [ ] Convert all string scors to int values
- [ ] Track, location vs popularity
- [ ] Understand from which region of the country students are most satisfied or dissatisfied 


In [5]:
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].unique()

array([nan, 10.,  9.,  3.,  8.,  6.,  7.,  4.,  5.])

In [10]:
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].isna()

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
       ... 
962    True
963    True
964    True
965    True
966    True
967    True
968    True
969    True
970    True
971    True
972    True
973    True
974    True
975    True
976    True
977    True
978    True
979    True
980    True
981    True
982    True
983    True
984    True
985    True
986    True
987    True
988    True
989    True
990    True
991    True
Name: How likely is it that you would recommend the Make School Summer Academy to a friend?, Length: 992, dtype: bool

In [6]:
df['How well is the schedule paced?'].unique()

array([3, 4, 1, 2, 5, nan, '2', '3', '4', '5', '#REF!'], dtype=object)

In [7]:
# Available tracks are Intro, Games, Apps and VR
df['What track are you in?'].unique()

array([nan, 'Intro', 'Games', 'Apps', 'VR', 'Average:'], dtype=object)

In [4]:
# Available locations are New York, San Francisco, Sunnyvale, Singapore and Los Angeles
df['location'].unique()

array([nan, 'New York', 'San Francisco', 'Sunnyvale', 'Singapore',
       'Los Angeles'], dtype=object)

In [5]:
df['How well are the tutorials paced?'].unique()

array([nan,  3.,  4.,  5.,  2.])

## Data Cleaning/Manipulation on the 2017 Data

In [8]:
path_2017 = "./SA Feedback Surveys_FINAL/2017/Student Feedback Surveys-Superview.csv"
data_2017 = pd.read_csv(path_2017)

### In order to ensure our empty data in our Schedule Pacing column does not contort our findings, we'll replace the NaNs with a "harmless" value with a datatype that matches the rest of our column.

In this case, since we want to convert our strings to ints, we'll turn our NaNs into ints outside of our expected useful range. 

Since we want to end up with a range of [1, 5], we'll give our NaN values a value of 0. 

In [9]:
data_2017["Schedule Pacing"].unique()

array(['Just right', 'A little too fast', 'Way too slow',
       'A little too slow', 'Way too fast', nan], dtype=object)

## Clever Data Cleaning for _Scheduling Pacing_

In [10]:
def clean_schedule_pacing_2017(data_2017):
    """ Function designed to clean NaNs and convert strings to ints across Scheduling Pacing column of DF 2017. """
    pacing_map = {
        "Way too slow": 1,
        "A little too slow": 2,
        "Just right": 3,
        "A little too fast": 4,
        "Way too fast": 5
    }
    data_2017["Schedule Pacing"] = data_2017["Schedule Pacing"].replace(pacing_map).fillna(0).astype(int)
    return data_2017

## NOTE: Only call this function when cleaning newly initialized 2017 data.

In [11]:
data_2017 = clean_schedule_pacing_2017(data_2017)

In [12]:
data_2017["Schedule Pacing"].unique()

array([3, 4, 1, 2, 5, 0])

In [13]:
# unique_vals = set()

# for value in data_2017["Rating (Num)"]:
#     unique_vals.update([type(value)])

def replace_errors_in_ratings_2017(data_2017):
    arg_all_but_errors = (data_2017["Rating (Num)"] != "#ERROR!")
    data_2017 = data_2017[arg_all_but_errors]
    data_2017["Rating (Num)"] = data_2017["Rating (Num)"].astype(int)
    return data_2017

In [14]:
data_2017 = replace_errors_in_ratings_2017(data_2017)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [15]:
data_2017["Rating (Num)"].unique()

array([ 3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2])

In [17]:
data_2017["Week"].unique()

array(['Week 1', 'Week 2', 'Week 7', 'Week 3', 'Week 4', 'Week 5',
       'Week 6', 'Week 8'], dtype=object)

In [20]:
data_2017["Track"] = data_2017["Track"].fillna('Track')

In [28]:
data_2017["Track"].unique()

array(['Apps, Explorer', 'Apps', 'Games', 'Track', 'VR',
       'Games, Explorer'], dtype=object)

In [31]:
# df[(df['Sex'] == 'female')].Age.hist(bins=16)
data_2017[(data_2017["Track"] == 'Apps, Explorer')].count()

ID                 224
Location           224
Track              224
Week               224
Rating (Num)       224
Schedule Pacing    224
dtype: int64

In [32]:
data_2017.head()

ID       Location           Track    Week  Rating (Num)  Schedule Pacing
0  134  San Francisco  Apps, Explorer  Week 1             3                3
1   36    Los Angeles            Apps  Week 1             4                4
2  117  San Francisco           Games  Week 1             4                1
3  253            NaN           Track  Week 2             4                4
4  350  New York City  Apps, Explorer  Week 1             4                3

In [35]:
data_2017["Location"].unique()

array(['San Francisco', 'Los Angeles', 'Location', 'New York City',
       'Redwood City', 'Santa Clara', 'Oakland', 'Washington DC',
       'Chicago', 'Atlanta', 'Hong Kong', 'Beijing', 'Tokyo'],
      dtype=object)

In [34]:
data_2017["Location"] = data_2017["Location"].fillna('Location')

In [36]:
data_2017["ID"].unique()

array([ 134,   36,  117, ..., 1497, 1498, 1499])

In [41]:
# pd.isnull(df.Age).sum()
pd.isnull(data_2017.ID).sum()

0

In [42]:
data_2017.head()

ID       Location           Track    Week  Rating (Num)  Schedule Pacing
0  134  San Francisco  Apps, Explorer  Week 1             3                3
1   36    Los Angeles            Apps  Week 1             4                4
2  117  San Francisco           Games  Week 1             4                1
3  253       Location           Track  Week 2             4                4
4  350  New York City  Apps, Explorer  Week 1             4                3

## Data Cleaning/Manipulation on the 2017 Week 8 Data

In [143]:
csv_2016 = glob.glob(os.path.join('./SA Feedback Surveys_FINAL/2016/', "*.csv"))
read_all_csvs = (pd.read_csv(f) for f in csv_2016)
data_2016 = pd.concat(read_all_csvs, ignore_index = True, sort = True)

# path_2016 = "./SA Feedback Surveys_FINAL/2016/*.csv"
# data_2016 = pd.read_csv(path_2016)

In [144]:
data_2016


#  \
0    NaN   
1    NaN   
2    NaN   
3    NaN   
4    NaN   
5    NaN   
6    NaN   
7    NaN   
8    NaN   
9    NaN   
10   NaN   
11   NaN   
12   NaN   
13   NaN   
14   NaN   
15   NaN   
16   NaN   
17   NaN   
18   NaN   
19   NaN   
20   NaN   
21   NaN   
22   NaN   
23   NaN   
24   NaN   
25   NaN   
26   NaN   
27   NaN   
28   NaN   
29   NaN   
..   ...   
962  NaN   
963  NaN   
964  NaN   
965  NaN   
966  NaN   
967  NaN   
968  NaN   
969  NaN   
970  NaN   
971  NaN   
972  NaN   
973  NaN   
974  NaN   
975  NaN   
976  NaN   
977  NaN   
978  NaN   
979  NaN   
980  NaN   
981  NaN   
982  NaN   
983  NaN   
984  NaN   
985  NaN   
986  NaN   
987  NaN   
988  NaN   
989  NaN   
990  NaN   
991  NaN   

     How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                  NaN                                       
1                                                  NaN                                       
2                                                  NaN                                       
3                                                  NaN                                       
4                                                  NaN                                       
5                                                  NaN                                       
6                                                  NaN                                       
7                                                  NaN                                       
8                                                  NaN                                       
9                                                  NaN                                       
10                                                 NaN                                       
11                                                 NaN                                       
12                                                 NaN                                       
13                                                 NaN                                       
14                                                 NaN                                       
15                                                 NaN                                       
16                                                 NaN                                       
17                                                 NaN                                       
18                                                 NaN                                       
19                                                 NaN                                       
20                                                 NaN                                       
21                                                 NaN                                       
22                                                 NaN                                       
23                                                 NaN                                       
24                                                 NaN                                       
25                                                 NaN                                       
26                                                 NaN                                       
27                                                 NaN                                       
28                                                 NaN                                       
29                                                 NaN                                       
..                                                 ...                                       
962                                                NaN                                       
963                                                NaN                                       
964                                                NaN            

In [145]:
def replace_errors_in_ratings_2016(data_2016):
    arg_all_but_errors = (data_2016["How well is the schedule paced?"] != "#REF!")
    data_2016 = data_2016[arg_all_but_errors]
    return data_2016

In [146]:
data_2016 = replace_errors_in_ratings_2016(data_2016)

In [147]:
data_2016

#  \
0    NaN   
1    NaN   
2    NaN   
3    NaN   
4    NaN   
5    NaN   
6    NaN   
7    NaN   
8    NaN   
9    NaN   
10   NaN   
11   NaN   
12   NaN   
13   NaN   
14   NaN   
15   NaN   
16   NaN   
17   NaN   
18   NaN   
19   NaN   
20   NaN   
21   NaN   
22   NaN   
23   NaN   
24   NaN   
25   NaN   
26   NaN   
27   NaN   
28   NaN   
29   NaN   
..   ...   
961  NaN   
962  NaN   
963  NaN   
964  NaN   
965  NaN   
966  NaN   
967  NaN   
968  NaN   
969  NaN   
970  NaN   
971  NaN   
972  NaN   
973  NaN   
974  NaN   
975  NaN   
976  NaN   
977  NaN   
978  NaN   
979  NaN   
980  NaN   
981  NaN   
982  NaN   
983  NaN   
984  NaN   
985  NaN   
986  NaN   
987  NaN   
989  NaN   
990  NaN   
991  NaN   

     How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                  NaN                                       
1                                                  NaN                                       
2                                                  NaN                                       
3                                                  NaN                                       
4                                                  NaN                                       
5                                                  NaN                                       
6                                                  NaN                                       
7                                                  NaN                                       
8                                                  NaN                                       
9                                                  NaN                                       
10                                                 NaN                                       
11                                                 NaN                                       
12                                                 NaN                                       
13                                                 NaN                                       
14                                                 NaN                                       
15                                                 NaN                                       
16                                                 NaN                                       
17                                                 NaN                                       
18                                                 NaN                                       
19                                                 NaN                                       
20                                                 NaN                                       
21                                                 NaN                                       
22                                                 NaN                                       
23                                                 NaN                                       
24                                                 NaN                                       
25                                                 NaN                                       
26                                                 NaN                                       
27                                                 NaN                                       
28                                                 NaN                                       
29                                                 NaN                                       
..                                                 ...                                       
961                                                NaN                                       
962                                                NaN                                       
963                                                NaN            

In [148]:
data_2016.head()

#  \
0  NaN   
1  NaN   
2  NaN   
3  NaN   
4  NaN   

   How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                NaN                                       
1                                                NaN                                       
2                                                NaN                                       
3                                                NaN                                       
4                                                NaN                                       

   How well are the tutorials paced? How well is the schedule paced?  \
0                                NaN                               3   
1                                NaN                               3   
2                                NaN                               3   
3                                NaN                               4   
4                                NaN                               4   

  How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                  3                                
1                                                  4                                
2                                                  4                                
3                                                  4                                
4                                                  5                                

  Network ID Start Date (UTC) Submit Date (UTC)         Timestamp Unnamed: 0  \
0        NaN              NaN               NaN  8/5/2016 1:39:41        NaN   
1        NaN              NaN               NaN  8/5/2016 1:40:47        NaN   
2        NaN              NaN               NaN  8/5/2016 1:40:50        NaN   
3        NaN              NaN               NaN  8/5/2016 1:42:44        NaN   
4        NaN              NaN               NaN  8/5/2016 1:45:13        NaN   

  What track are you in? location track  
0                    NaN      NaN   NaN  
1                    NaN      NaN   NaN  
2                    NaN      NaN   NaN  
3                    NaN      NaN   NaN  
4                    NaN      NaN   NaN

In [149]:
data_2017.head()

ID       Location           Track    Week Rating (Num)    Schedule Pacing
0  134  San Francisco  Apps, Explorer  Week 1            3         Just right
1   36    Los Angeles            Apps  Week 1            4  A little too fast
2  117  San Francisco           Games  Week 1            4       Way too slow
3  253            NaN             NaN  Week 2            4  A little too fast
4  350  New York City  Apps, Explorer  Week 1            4         Just right

In [150]:
# Remove columns with no real information
data_2016 = data_2016.drop(["Unnamed: 0", "#", "Network ID"], axis=1)

In [151]:
data_2016.head()

How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                NaN                                       
1                                                NaN                                       
2                                                NaN                                       
3                                                NaN                                       
4                                                NaN                                       

   How well are the tutorials paced? How well is the schedule paced?  \
0                                NaN                               3   
1                                NaN                               3   
2                                NaN                               3   
3                                NaN                               4   
4                                NaN                               4   

  How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                  3                                
1                                                  4                                
2                                                  4                                
3                                                  4                                
4                                                  5                                

  Start Date (UTC) Submit Date (UTC)         Timestamp What track are you in?  \
0              NaN               NaN  8/5/2016 1:39:41                    NaN   
1              NaN               NaN  8/5/2016 1:40:47                    NaN   
2              NaN               NaN  8/5/2016 1:40:50                    NaN   
3              NaN               NaN  8/5/2016 1:42:44                    NaN   
4              NaN               NaN  8/5/2016 1:45:13                    NaN   

  location track  
0      NaN   NaN  
1      NaN   NaN  
2      NaN   NaN  
3      NaN   NaN  
4      NaN   NaN

In [152]:
data_2016["track"].unique()

array([nan, 'summerApps', 'summerIntro', 'summerApps (4-week)',
       'summerGames', 'summerVR', 'summerGames (4-week)'], dtype=object)

In [153]:
data_2016["How likely is it that you would recommend the Make School Summer Academy to a friend?"] = data_2016["How likely is it that you would recommend the Make School Summer Academy to a friend?"].fillna("0").astype(int)

In [154]:
data_2016["How well are the tutorials paced?"] = data_2016["How well are the tutorials paced?"].fillna(0).astype(int)

In [155]:
data_2016["How well is the schedule paced?"] = data_2016["How well are the tutorials paced?"].fillna(0).astype(int)

In [156]:
data_2016["How would you rate your overall satisfaction with the Summer Academy this week?"] = data_2016["How would you rate your overall satisfaction with the Summer Academy this week?"].fillna(0).astype(int)

In [157]:
data_2016

How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                    0                                       
1                                                    0                                       
2                                                    0                                       
3                                                    0                                       
4                                                    0                                       
5                                                    0                                       
6                                                    0                                       
7                                                    0                                       
8                                                    0                                       
9                                                    0                                       
10                                                   0                                       
11                                                   0                                       
12                                                   0                                       
13                                                   0                                       
14                                                   0                                       
15                                                   0                                       
16                                                   0                                       
17                                                   0                                       
18                                                   0                                       
19                                                   0                                       
20                                                   0                                       
21                                                   0                                       
22                                                   0                                       
23                                                   0                                       
24                                                   0                                       
25                                                   0                                       
26                                                   0                                       
27                                                   0                                       
28                                                   0                                       
29                                                   0                                       
..                                                 ...                                       
961                                                  0                                       
962                                                  0                                       
963                                                  0                                       
964                                                  0                                       
965                                                  0                                       
966                                                  0                                       
967                                                  0                                       
968                                                  0                                       
969                                                  0                                       
970                                                  0                                       
971                                                  0   

In [158]:
data_2016["track"].unique()

array([nan, 'summerApps', 'summerIntro', 'summerApps (4-week)',
       'summerGames', 'summerVR', 'summerGames (4-week)'], dtype=object)

In [159]:
data_2016["What track are you in?"].unique()

array([nan, 'Intro', 'Games', 'Apps', 'VR'], dtype=object)

In [160]:
data_2016["Track"] = data_2016["What track are you in?"].str.cat(data_2016['track'], na_rep="")

In [161]:
data_2016["Track"].unique()

array(['', 'Intro', 'Games', 'Apps', 'VR', 'summerApps', 'summerIntro',
       'summerApps (4-week)', 'summerGames', 'summerVR',
       'summerGames (4-week)'], dtype=object)

In [162]:
data_2016 = data_2016.drop(["track", "What track are you in?"], axis=1)

In [141]:
# w['female'] = w['female'].map({'female': 1, 'male': 0})
# w.loc[w.female == 'female', 'female'] = 1

data_2016.loc[data_2016.Track == ""]

In [142]:
data_2016["Track"].unique()

array([nan], dtype=object)