### Data Cleaning Questions

- How do we consolidate `Week` and `Location` data from the 2016 filenames to the final 2016 DataFrame?

## Steps for Cleaning All Data:
---
- Step 1: Clean the 2016 Data (Weeks 1-7) into One DataFrame.
- Step 2: Clean the 2016 Data (Weeks 8) into One DataFrame.
- Step 2.5: Aggregate both 2016 Datasets (Weeks 1-7 and Week 8) into One Bigger DF (Weeks 1-8).
- Step 3: Clean the 2017 Data into One DataFrame.
- Step 3.5: Aggregate the 2016 DataFrame (Weeks 1-8) and the 2017 DF into One Biggest DF (2016-17). 


### Observation that 4/5 may not be exactly equivalent to 8/10 as it is to 9/10...

- [`STRETCH`] Try both scenarios on any related questions!

## What is Cleaning?

- Some data might be irrelevant, redundant, null, nonsensical
- Cleaning involves the steps to reduce the noise in a dataset
- CLEANING: Converting a ton of noise, extracting _signal_, and ending up with a **single source of truth**
- Signal is data that is valuable towards answering a question; extracting signal is our end goal in all types of data science


# Kash Cleaning Tips


### Understand what a column (feature) is truly communicating 
- Examples: [1-5] scale vs. [1-10] vs. "A little too slow" text scale, 

### NULL Values (NaNs)
- 

In [10]:
import glob
import pandas as pd 
import numpy as np
import os

In [26]:
# df16 = [pd.read_csv(f) for f in glob.glob('./SA Feedback Surveys_FINAL/2016/*.csv')]

all_csvs = glob.glob(os.path.join('./SA Feedback Surveys_FINAL/2016/', "*.csv"))
read_all_csvs = (pd.read_csv(f) for f in all_csvs)
df = pd.concat(read_all_csvs, ignore_index = True, sort = True)
df.head()

the_bad_thing = np.nan
type(the_bad_thing)

float

# To-Do List
- [ ] Check all columns to see if they have valid responses
- [ ] #REF! rows invalid
- [ ] Convert all string scors to int values
- [ ] Track, location vs popularity
- [ ] Understand from which region of the country students are most satisfied or dissatisfied 


In [5]:
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].unique()

array([nan, 10.,  9.,  3.,  8.,  6.,  7.,  4.,  5.])

In [10]:
df['How likely is it that you would recommend the Make School Summer Academy to a friend?'].isna()

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
       ... 
962    True
963    True
964    True
965    True
966    True
967    True
968    True
969    True
970    True
971    True
972    True
973    True
974    True
975    True
976    True
977    True
978    True
979    True
980    True
981    True
982    True
983    True
984    True
985    True
986    True
987    True
988    True
989    True
990    True
991    True
Name: How likely is it that you would recommend the Make School Summer Academy to a friend?, Length: 992, dtype: bool

In [9]:
df['How well is the schedule paced?'].unique()

array([3, 4, 1, 2, 5, nan, '2', '3', '4', '5', '#REF!'], dtype=object)

In [3]:
# Available tracks are Intro, Games, Apps and VR
df['What track are you in?'].unique()

array([nan, 'Intro', 'Games', 'Apps', 'VR', 'Average:'], dtype=object)

In [4]:
# Available locations are New York, San Francisco, Sunnyvale, Singapore and Los Angeles
df['location'].unique()

array([nan, 'New York', 'San Francisco', 'Sunnyvale', 'Singapore',
       'Los Angeles'], dtype=object)

In [5]:
df['How well are the tutorials paced?'].unique()

array([nan,  3.,  4.,  5.,  2.])

## Data Cleaning/Manipulation on the 2017 Data

In [85]:
path_2017 = "./SA Feedback Surveys_FINAL/2017/Student Feedback Surveys-Superview.csv"
data_2017 = pd.read_csv(path_2017)

### In order to ensure our empty data in our Schedule Pacing column does not contort our findings, we'll replace the NaNs with a "harmless" value with a datatype that matches the rest of our column.

In this case, since we want to convert our strings to ints, we'll turn our NaNs into ints outside of our expected useful range. 

Since we want to end up with a range of [1, 5], we'll give our NaN values a value of 0. 

In [86]:
data_2017["Schedule Pacing"].unique()

array(['Just right', 'A little too fast', 'Way too slow',
       'A little too slow', 'Way too fast', nan], dtype=object)

## Clever Data Cleaning for _Scheduling Pacing_

In [87]:
def clean_schedule_pacing_2017(data_2017):
    """ Function designed to clean NaNs and convert strings to ints across Scheduling Pacing column of DF 2017. """
    pacing_map = {
        "Way too slow": 1,
        "A little too slow": 2,
        "Just right": 3,
        "A little too fast": 4,
        "Way too fast": 5
    }
    data_2017["Schedule Pacing"] = data_2017["Schedule Pacing"].replace(pacing_map).fillna(0).astype(int)
    return data_2017

## NOTE: Only call this function when cleaning newly initialized 2017 data.

In [88]:
data_2017 = clean_schedule_pacing_2017(data_2017)

In [89]:
data_2017["Schedule Pacing"].unique()

array([3, 4, 1, 2, 5, 0])

In [93]:
# unique_vals = set()

# for value in data_2017["Rating (Num)"]:
#     unique_vals.update([type(value)])

def replace_errors_in_ratings_2017(data_2017):
    arg_all_but_errors = (data_2017["Rating (Num)"] != "#ERROR!")
    data_2017 = data_2017[arg_all_but_errors]
    data_2017["Rating (Num)"] = data_2017["Rating (Num)"].astype(int)
    return data_2017

In [94]:
data_2017 = replace_errors_in_ratings_2017(data_2017)

In [95]:
data_2017["Rating (Num)"].unique()

array([ 3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2])